### ISSUE TITLE
iOS26 issues

### ISSUE THREAD

**Issue by chrisip1605** [mongoose-os-apps/shelly-homekit#1728]
Till this morning every was running fine since years.
All my Apple Devices automatically made the Softwareupdate to iOS26.2 this night(i already deactivated automatic updates).
So my HomePodMinis, iPad and iPhone15Pro running on iOS26.2 now.
Since then the Shelly-HomeKit Garage is offline in AppleHome.
I tried rebooting all Devices - Apple Devices and Shelly. Still not working.
Tried to remove the Garagedoor from AppleHome. Now i can't reconnect the Garagedoor to AppleHome with any device. Also tried the iPad of my girl running iOS 18.7.2 no success
Tried to Reset the System and reconfigured everything. Still not working.
Further i can't acces the Webpannel with any Device via Safari. - Saying "Loading..." and with a red frame "Disconnected".
With Firefox  can acces the Webinterface with any device.

All Apple Devices running iOS26.2
Shelly used: ShellyMini1Gen3
Version:2.14.3
Build: 20250723-051653 

[Log.txt](https://github.com/user-attachments/files/24142969/Log.txt) in clear text below- 192.168.1.53 is my Notebook; 192.168.1.40 Shelly

Thank you guys for your help!
Greetings from Austria!

<img width="295" height="639" alt="Image" src="https://github.com/user-attachments/assets/7fb2ab77-beb7-444a-9d75-601cddd000c4" />

<img width="295" height="639" alt="Image" src="https://github.com/user-attachments/assets/4285296e-3136-403e-8fbb-3cc10244c064" />

52451988975 shelly_debug.cpp:231    No log file, sending new entries
52458292182 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52459300784 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52459594810 shelly_main.cpp:495     Up 52459.58, HAP 0/0/16 ns 0, RAM: 203720/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52461458239 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52462460933 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52463715504 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52464669684 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52465591764 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52466524518 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52467594767 shelly_main.cpp:495     Up 52467.58, HAP 0/0/16 ns 0, RAM: 203720/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52475594805 shelly_main.cpp:495     Up 52475.58, HAP 0/0/16 ns 0, RAM: 203720/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52483594742 shelly_main.cpp:495     Up 52483.58, HAP 0/0/16 ns 0, RAM: 203380/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52487912238 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52488918442 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52489116229 mg_rpc.c:315            HAP.Setup via WS_in 192.168.1.53:50275
52491341129 mgos_sys_config.c:323   Saved to conf2.json
52491346060 mgos_homekit_adk_rp:261 Stopping server for reset
52491353749 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52491365343 shelly_main.cpp:387     HAP server state: 2
52491374279 HAPPlatformTCPStrea:112 0x3fcaee8c 0.0.0.0:9004 HAP connection closed, ns 0/0/16 i 1
52491379554 shelly_main.cpp:387     HAP server state: 0
52491384220 shelly_main.cpp:360     === Destroying accessories
52491450367 mgos_homekit_adk_rp:272 Resetting server
52491472986 shelly_main.cpp:301     === Creating accessories
52491477496 shelly_hap_garage_d:103 GDO 1: cur_state 0
52491539200 shelly_main.cpp:338     === Starting HAP server (ID 7C:04:DF:83:15:0B, UUID <n/a>, CN 1)
52491712631 HAPPlatformTCPStrea:187 Listening on 9005
52491718719 shelly_main.cpp:387     HAP server state: 1
52491726898 shelly_hap_garage_d:321 GDO 1: Tgt State: open -> closed (0 -> 1) (ext)
52491732994 shelly_hap_garage_d:235 GDO 1: Cur State: open -> closed (0 -> 1)
52491914266 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52492940397 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52493371310 shelly_main.cpp:495     Up 52493.36, HAP 0/0/16 ns 0, RAM: 203356/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52493950941 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52494969884 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52495979507 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52496991018 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52498002843 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52499011244 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52500024057 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52501026508 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52501371255 shelly_main.cpp:495     Up 52501.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52502033427 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52503041562 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52504047782 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52505053682 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52506066151 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52507071965 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:50275
52509371296 shelly_main.cpp:495     Up 52509.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52517371248 shelly_main.cpp:495     Up 52517.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52525371249 shelly_main.cpp:495     Up 52525.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52533371251 shelly_main.cpp:495     Up 52533.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52541371267 shelly_main.cpp:495     Up 52541.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52549371251 shelly_main.cpp:495     Up 52549.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52557371300 shelly_main.cpp:495     Up 52557.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52565371252 shelly_main.cpp:495     Up 52565.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52573371240 shelly_main.cpp:495     Up 52573.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52581371251 shelly_main.cpp:495     Up 52581.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52589371246 shelly_main.cpp:495     Up 52589.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52597371251 shelly_main.cpp:495     Up 52597.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52605371251 shelly_main.cpp:495     Up 52605.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52613371253 shelly_main.cpp:495     Up 52613.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52621371324 shelly_main.cpp:495     Up 52621.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52629371250 shelly_main.cpp:495     Up 52629.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52637371231 shelly_main.cpp:495     Up 52637.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52645371244 shelly_main.cpp:495     Up 52645.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52653371251 shelly_main.cpp:495     Up 52653.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52661371250 shelly_main.cpp:495     Up 52661.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52669371247 shelly_main.cpp:495     Up 52669.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52677371250 shelly_main.cpp:495     Up 52677.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52685371312 shelly_main.cpp:495     Up 52685.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52693371268 shelly_main.cpp:495     Up 52693.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52701371248 shelly_main.cpp:495     Up 52701.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52709371246 shelly_main.cpp:495     Up 52709.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52717371247 shelly_main.cpp:495     Up 52717.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52725371244 shelly_main.cpp:495     Up 52725.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52733371255 shelly_main.cpp:495     Up 52733.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52741371247 shelly_main.cpp:495     Up 52741.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52749371306 shelly_main.cpp:495     Up 52749.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52757371273 shelly_main.cpp:495     Up 52757.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52765371248 shelly_main.cpp:495     Up 52765.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52773371260 shelly_main.cpp:495     Up 52773.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52781371258 shelly_main.cpp:495     Up 52781.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52789371246 shelly_main.cpp:495     Up 52789.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52797371253 shelly_main.cpp:495     Up 52797.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52805371251 shelly_main.cpp:495     Up 52805.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52813371254 shelly_main.cpp:495     Up 52813.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52821371286 shelly_main.cpp:495     Up 52821.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52829371205 shelly_main.cpp:495     Up 52829.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52837371257 shelly_main.cpp:495     Up 52837.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52845371260 shelly_main.cpp:495     Up 52845.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52853371255 shelly_main.cpp:495     Up 52853.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1
52861371251 shelly_main.cpp:495     Up 52861.36, HAP 0/0/16 ns 0, RAM: 203696/186092; st 33; 5.1: cur:closed tgt:closed cl:1 op:-1

**Comment by markirb** [comment]
The webinterface seems to be duplicate of this one:

https://github.com/mongoose-os-apps/shelly-homekit/issues/1690

Probably a newly introduced http library incompatibility in safari and mongoose...

Otherwise 26.2 seems to be working fine for me.

**Comment by chrisip1605** [comment]
Okay, thanks for your reply, lib makes sense to me. But if all your devices also running iOS26.2 and working fine, what could be the issiue at my system for not responding and not beeing able to re-add it to my HomeKit all of sudden 🤔 I am not aware of having changed anything else.

**Comment by markirb** [comment]
The WebKit/Safari error seems to related to Websockets and is according to research illegal (not following http standard) behaviour by apple so it is a Bug in their side. 

I had the experience that if I left the page open then after a while it was working.

Websockets is not related to HomeKit so the pairing has to be another thing

**Comment by chrisip1605** [comment]
Got that, I can work via Firefox if I need the webinterface for pairing-code.

U got any other idea what i could try to get it into HomeKit again?

**Comment by stodla123** [comment]
Hello

MacOS 26 seems to be affected as well:


<img width="1138" height="938" alt="Image" src="https://github.com/user-attachments/assets/33d67c5e-cb79-41df-a129-88033377bb37" />

Logs can be provided if needed.

Greetings from Austria as well ;-)

**Comment by chrisip1605** [comment]
Updated iPhone to 26.2.1
Still not able to add to HomeKit.

Screenrecord of failing to add:
https://1drv.ms/v/c/182a32ee41772814/IQCRCm5XxeRWRavOpGHkeVa4AYhluGUSWz70cesuNWSMAJI

Log:
> 2793186125846 shelly_debug.cpp:231    No log file, sending new entries
2793186617687 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:54729
2793187574329 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:54729
2793191510584 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:54729
2793192394380 shelly_main.cpp:495     Up 2793192.38, HAP 0/0/16 ns 0, RAM: 203324/174596; st 29; 5.1: cur:closed tgt:closed cl:1 op:-1
2793192476305 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:54729
2793193453592 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.1.53:54729

**Comment by psionic001** [comment]
Same problem here 
Won’t work in HomeKit
Says disconnected in Safari
Works fine in iOS Chrome

**Comment by sinabuddy** [comment]
I have the same Problem: won‘t work at the moment…

**Comment by chrisip1605** [comment]
I have 2 garage-door-opener at another house. Didn't plan to make the update to iOS 26 there jet.
But today the Homepod made the update to HomePodOS 26.2 by accident. - Shelly-HomeKit wasn't working anymore. Did not remove the HomeKit accessory, just tried what will happen when i update the HomePod to 26.3.
To my suprise, got it working with HomeKit again.
So HomepodOS 26.3 and Shelly-HomeKit 2.14.2 is working, as long as it is still connected with HomeKit and not removed.

Is there a way to revert Shelly-HomeKit from 2.14.3 back to 2.14.2 ? 
I would like to try to revert the Firmware at my main-home with iOS 26.3 running at all devices. Wanna see if i can add it to HomeKit with this Version again.

**Comment by chrisip1605** [comment]
Updated iPhone to iOS 26.3.1 - still not able to add to HomeKit.

**Comment by vkristof1995** [comment]
I've opened a PR that should fix the Safari disconnection issue: #1738

The root cause is that Safari 26 changed its WebSocket handshake behavior in a way that's incompatible with the mongoose HTTP library. Since we can't easily update the embedded mongoose library, the fix adds an automatic HTTP fallback: after 2 failed WebSocket attempts, the web interface switches to using HTTP POST requests to the existing `/rpc` endpoint for all RPC communication. This is transparent to the user — the interface works the same way, just over HTTP instead of WebSocket.

This is a frontend-only change, so no firmware rebuild is needed beyond regenerating the `index.html.gz` from the updated `script.js`.

Would appreciate if affected users could test this.

**Comment by markirb** [comment]
Very good idea for a fix. I will try when I find time but it would be great if users here could give feedback as well.

**Comment by chrisip1605** [comment]
Is there somewhere a "How-To" to test it?

If i got it right, this won't solve the main issiue of this request.
Your improvement is a change in the frontend, which may solve the problem with the Safari disconnection message. - Without a doubt, that's also a problem.

But here the main problem is, i guess, somewhere in the backend, which makes it impossible to add the "Shelly-HomeKit" to Apple-Homekit.
Or is the problem of the web interface somehow linked to the problem not beeing able to add to Apple-Homekit?

Just tried to update all my apple hardware to iOS26.4 - still no success.

**Comment by iiseppi** [comment]
So, is this problem only with newer Shelly devices? I have couple original Shelly 1 and they are running with firmware 2.14.3. No problem with accessing them via Safari or Apple Home app.

**Comment by chrisip1605** [comment]
Updated my devices to 25.5
Seems like Apple finally solved the visualizing bug. You can now load and reload the webinterface again without „disconnected“ message.

But the main problem of this topic: not able to connect shelly-HomeKit to Apple HomeKit is still not solved!

**Comment by chrisip1605** [comment]
> So, is this problem only with newer Shelly devices? I have couple original Shelly 1 and they are running with firmware 2.14.3. No problem with accessing them via Safari or Apple Home app.

Once it‘s paired to apple homekit it‘s no problem. But try to delete the shelly-homekit accesory from your apple homekit. You won‘t be able to add it back to apple homekit…

**Comment by markirb** [comment]
is resolved with latest iOS update
